spring.application.name=foodsbackend

# Database configuration
Server.port=8080
Spring.datasource.url=jdbc:mysql://localhost:3306/perupalem_foods_db
Spring.datasource.username=root
Spring.datasource.password=Root@1234

Spring.jpa.hibernate.ddl-auto=none

jwt.secret_key=Evm3LrL3XIIOsMNczOwa2lxzWDyg6IRA1DKpgCRmbMpwrPBcgU9lxQjF68W4pyLU1BtH+92cZhROwR5zl8CCQg==